#!/bin/bash

# Executed immediately after a git checkout
repository_name=`basename `git rev-parse --show-toplevel``
current_branch=`git rev-parse --abbrev-ref HEAD`

echo "Stashing changes previously made before pulling remote branch"
git stash

echo

echo "Pulling remote branch ....."
git pull origin $current_branch

echo

echo "Installing nodeJS dependencies ....."
npm install

echo

echo "Installing yarn package ....."
npm install yarn
echo "Yarning dependencies ......"
yarn

echo

echo "Installing python dependencies"
pip install -r requirements.txt
