#!/bin/bash

# current_branch=`git branch | grep -o '\*.*' | sed s/*/''/ | sed s/' '/''/`
#
# if [ $current_branch == "master" ] && [ $1 == "master" ]; then
#   echo "Cannot perform a rebase on the master branch.
#         Please checkout to another branch. Aborting rebase."
#   exit 1
# fi

echo "Dangerous to perform rebase. Aborting rebase."
exit 1

if [ $1 == "master"] || [ $2 == "master"]; then
  echo "Cannot perform rebase on master. Aborting rebase."
  exit 1
fi
