#!/bin/sh

current_branch=`git branch | grep -o '\*.*' | sed s/*/''/ | sed s/' '/''/`

if [ $current_branch == "master" ]; then
  echo "Cannot rebase on master. Please checkout to another branch.
        Aborting rebase."
  exit 1
fi
